### ISSUE TITLE
Sync service fails to update all movies in db

### ISSUE THREAD

**Issue by manekenpix** [chorizoft/cinesync#91]
Due to recent changes in our api, an empty request to the movie service returns 10 movies. The sync service uses the movie service to fetch movies from our db and check their etags agains tmdb's api, and with our change only the first 10 returned movies are checked.

We could try to use the solution in #77 for this.

**Comment by chrispinkney** [comment]
FML I didn't even think about this, sounds good I'll take a look soon 👍

**Comment by chrispinkney** [comment]
closed by #96
